### ISSUE TITLE
MD5 Hash needs PowerShell 4

### ISSUE THREAD

**Issue by CaptainCow95** [cake-build/resources#8]
I went to try out the new MD5 additions to the PowerShell bootstrapper script and found out that it doesn't work on my machine (running PowerShell 3). It appears that Get-FileHash only works on PowerShell 4 and higher. Is it now expected to be on at least PowerShell 4 or are you still supporting lower versions as I see a commit right after the MD5 addition for PowerShell 2 support it looks.

**Comment by gep13** [comment]
@CaptainCow95 hmm, supporting PowerShell 2 is definitely something that we want to support. I didn't know (I.e. I hadn't checked to see) if that cmdlet was supported. We will have to do something to correct that. Thanks for bringing it you our attention.

**Comment by devlead** [comment]
Good catch, we could probably be backwards compatible by reaching out to .Net classes.

**Comment by devlead** [comment]
@CaptainCow95 @gep13 think I have a fix for this, will submit a PR tonight that we can test.

**Comment by devlead** [comment]
Started submitting pull requests, also found and resolved an issue where the hash was saved even if the nuget install command failed.

- [x] Example - cake-build/cake#1079 
- [x] Website - cake-build/website#122
- [x] Example - cake-build/example#25
- [x] Resources- cake-build/resources#9
- [ ] Cake VSO - cake-build/cake-vso

**Comment by devlead** [comment]
@gep13 think I've addressed all mentioned places :)

**Comment by CaptainCow95** [comment]
Works for me now, thanks!

**Comment by devlead** [comment]
@CaptainCow95 splendid 👍 thanks for letting us know about the issue and for confirming it's fixed.
